// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzB390YVJNZ_W7dw6t86Nacda1bu4Ls4',
    appId: '1:883814116942:web:39b1d7f30fffc511641d1f',
    messagingSenderId: '883814116942',
    projectId: 'code-of-land',
    authDomain: 'code-of-land.firebaseapp.com',
    storageBucket: 'code-of-land.appspot.com',
    measurementId: 'G-S0YE5VR8D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHE1MOB_xdzRqXmJu8uUiVLtzBXuxFxI',
    appId: '1:883814116942:android:645170ac7ef5e465641d1f',
    messagingSenderId: '883814116942',
    projectId: 'code-of-land',
    storageBucket: 'code-of-land.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOePgugqDBpo41g6z68pvW1CB15J3LXT8',
    appId: '1:883814116942:ios:8a87f7fc907a0f22641d1f',
    messagingSenderId: '883814116942',
    projectId: 'code-of-land',
    storageBucket: 'code-of-land.appspot.com',
    iosClientId: '883814116942-erh4q8bsm50fnia2nd0nkdsv22bp1gke.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeOfLand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOePgugqDBpo41g6z68pvW1CB15J3LXT8',
    appId: '1:883814116942:ios:8a87f7fc907a0f22641d1f',
    messagingSenderId: '883814116942',
    projectId: 'code-of-land',
    storageBucket: 'code-of-land.appspot.com',
    iosClientId: '883814116942-erh4q8bsm50fnia2nd0nkdsv22bp1gke.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeOfLand',
  );
}
